name: Daily Data Refresh

on:
  schedule:
    # Run daily at 6:30 AM UTC (2:30 AM CST, adjust for your timezone)
    - cron: '30 6 * * *'
  workflow_dispatch:  # Allow manual trigger

jobs:
  refresh:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Fetch fresh data from APIs
      env:
        MOTIVE_API_KEY: ${{ secrets.MOTIVE_API_KEY }}
        KPA_API_TOKEN: ${{ secrets.KPA_API_TOKEN }}
      run: python fetch_data.py
    
    - name: Commit and push updated data
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add data/*.json
        git commit -m "Auto: Update safety data $(date +'%Y-%m-%d %H:%M:%S')" || echo "No changes to commit"
        git push
    
    - name: Notify on success
      run: echo "✓ Daily data refresh completed successfully at $(date +'%Y-%m-%d %H:%M:%S UTC')"
    
    - name: Notify on failure
      if: failure()
      run: echo "✗ Daily data refresh failed - check logs for details"
